[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    api: REST API automation tests
    ui: Playwright Page Object Model UI tests
    integration: E2E API-to-DB-to-UI integration tests
    health: PyATS and container network health check tests

addopts = --html=report.html --self-contained-html -v --tb=short
filterwarnings =
    ignore::DeprecationWarning
